### ISSUE TITLE
Snap not getting removed when running `remove-snap` role

### ISSUE THREAD

**Issue by ulticeng** [carldanley/homelab#1]
https://github.com/carldanley/homelab/blob/991ea9ae1949cc52565ee8c77f7845864dc74742/ansible/roles/remove-snap/tasks/main.yaml#L2

`snap` won't get removed unless `state` is set to `absent` in the `apt` configuration.

**Comment by carldanley** [comment]
Thanks! Fixed in https://github.com/carldanley/homelab/commit/e389be391b20884a9bc850ef2e7167b0e06267ad.
